// xSight gRPC service definition.
// Shared between Node (client) and Controller (server).
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: xsight.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeHandshake struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	NodeId                 string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ApiKey                 string                 `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Interfaces             []string               `protobuf:"bytes,3,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	AgentVersion           string                 `protobuf:"bytes,4,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	DeliveryVersionApplied uint64                 `protobuf:"varint,5,opt,name=delivery_version_applied,json=deliveryVersionApplied,proto3" json:"delivery_version_applied,omitempty"` // local snapshot version, 0 = none
	Mode                   string                 `protobuf:"bytes,6,opt,name=mode,proto3" json:"mode,omitempty"`                                                                      // "xdp" (default) | "flow" — v3.0
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *NodeHandshake) Reset() {
	*x = NodeHandshake{}
	mi := &file_xsight_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeHandshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeHandshake) ProtoMessage() {}

func (x *NodeHandshake) ProtoReflect() protoreflect.Message {
	mi := &file_xsight_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeHandshake.ProtoReflect.Descriptor instead.
func (*NodeHandshake) Descriptor() ([]byte, []int) {
	return file_xsight_proto_rawDescGZIP(), []int{0}
}

func (x *NodeHandshake) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeHandshake) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *NodeHandshake) GetInterfaces() []string {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

func (x *NodeHandshake) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *NodeHandshake) GetDeliveryVersionApplied() uint64 {
	if x != nil {
		return x.DeliveryVersionApplied
	}
	return 0
}

func (x *NodeHandshake) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type HandshakeResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Accepted               bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	RejectReason           string                 `protobuf:"bytes,2,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"`
	WatchConfig            *WatchConfig           `protobuf:"bytes,3,opt,name=watch_config,json=watchConfig,proto3" json:"watch_config,omitempty"`
	DeliveryVersionCurrent uint64                 `protobuf:"varint,4,opt,name=delivery_version_current,json=deliveryVersionCurrent,proto3" json:"delivery_version_current,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_xsight_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xsight_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_xsight_proto_rawDescGZIP(), []int{1}
}

func (x *HandshakeResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *HandshakeResponse) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

func (x *HandshakeResponse) GetWatchConfig() *WatchConfig {
	if x != nil {
		return x.WatchConfig
	}
	return nil
}

func (x *HandshakeResponse) GetDeliveryVersionCurrent() uint64 {
	if x != nil {
		return x.DeliveryVersionCurrent
	}
	return 0
}

type StatsReport struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	NodeId             string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	InterfaceName      string                 `protobuf:"bytes,2,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	UpstreamSampleRate uint32                 `protobuf:"varint,3,opt,name=upstream_sample_rate,json=upstreamSampleRate,proto3" json:"upstream_sample_rate,omitempty"`
	LocalSampleRate    uint32                 `protobuf:"varint,4,opt,name=local_sample_rate,json=localSampleRate,proto3" json:"local_sample_rate,omitempty"`
	Timestamp          int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // unix epoch seconds
	IpStats            []*IPStats             `protobuf:"bytes,6,rep,name=ip_stats,json=ipStats,proto3" json:"ip_stats,omitempty"`
	PrefixStats        []*PrefixStatsMsg      `protobuf:"bytes,7,rep,name=prefix_stats,json=prefixStats,proto3" json:"prefix_stats,omitempty"`
	Health             *NodeHealth            `protobuf:"bytes,8,opt,name=health,proto3" json:"health,omitempty"`
	SamplingMetrics    *SamplingMetrics       `protobuf:"bytes,9,opt,name=sampling_metrics,json=samplingMetrics,proto3" json:"sampling_metrics,omitempty"`
	GapSeconds         uint32                 `protobuf:"varint,10,opt,name=gap_seconds,json=gapSeconds,proto3" json:"gap_seconds,omitempty"` // data gap after reconnect
	IpStatsTruncated   bool                   `protobuf:"varint,11,opt,name=ip_stats_truncated,json=ipStatsTruncated,proto3" json:"ip_stats_truncated,omitempty"`
	TotalActiveIps     uint32                 `protobuf:"varint,12,opt,name=total_active_ips,json=totalActiveIps,proto3" json:"total_active_ips,omitempty"`
	GlobalStats        *GlobalStatsMsg        `protobuf:"bytes,13,opt,name=global_stats,json=globalStats,proto3" json:"global_stats,omitempty"`
	TopFlows           []*FlowSample          `protobuf:"bytes,20,rep,name=top_flows,json=topFlows,proto3" json:"top_flows,omitempty"` // top-N flows this tick
	// v2.11 Phase 2: outbound (src_ip matched) stats
	SrcIpStats          []*IPStats        `protobuf:"bytes,30,rep,name=src_ip_stats,json=srcIpStats,proto3" json:"src_ip_stats,omitempty"`
	SrcPrefixStats      []*PrefixStatsMsg `protobuf:"bytes,31,rep,name=src_prefix_stats,json=srcPrefixStats,proto3" json:"src_prefix_stats,omitempty"`
	SrcIpStatsTruncated bool              `protobuf:"varint,32,opt,name=src_ip_stats_truncated,json=srcIpStatsTruncated,proto3" json:"src_ip_stats_truncated,omitempty"`
	TotalActiveSrcIps   uint32            `protobuf:"varint,33,opt,name=total_active_src_ips,json=totalActiveSrcIps,proto3" json:"total_active_src_ips,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *StatsReport) Reset() {
	*x = StatsReport{}
	mi := &file_xsight_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsReport) ProtoMessage() {}

func (x *StatsReport) ProtoReflect() protoreflect.Message {
	mi := &file_xsight_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsReport.ProtoReflect.Descriptor instead.
func (*StatsReport) Descriptor() ([]byte, []int) {
	return file_xsight_proto_rawDescGZIP(), []int{2}
}

func (x *StatsReport) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *StatsReport) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *StatsReport) GetUpstreamSampleRate() uint32 {
	if x != nil {
		return x.UpstreamSampleRate
	}
	return 0
}

func (x *StatsReport) GetLocalSampleRate() uint32 {
	if x != nil {
		return x.LocalSampleRate
	}
	return 0
}

func (x *StatsReport) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *StatsReport) GetIpStats() []*IPStats {
	if x != nil {
		return x.IpStats
	}
	return nil
}

func (x *StatsReport) GetPrefixStats() []*PrefixStatsMsg {
	if x != nil {
		return x.PrefixStats
	}
	return nil
}

func (x *StatsReport) GetHealth() *NodeHealth {
	if x != nil {
		return x.Health
	}
	return nil
}

func (x *StatsReport) GetSamplingMetrics() *SamplingMetrics {
	if x != nil {
		return x.SamplingMetrics
	}
	return nil
}

func (x *StatsReport) GetGapSeconds() uint32 {
	if x != nil {
		return x.GapSeconds
	}
	return 0
}

func (x *StatsReport) GetIpStatsTruncated() bool {
	if x != nil {
		return x.IpStatsTruncated
	}
	return false
}

func (x *StatsReport) GetTotalActiveIps() uint32 {
	if x != nil {
		return x.TotalActiveIps
	}
	return 0
}

func (x *StatsReport) GetGlobalStats() *GlobalStatsMsg {
	if x != nil {
		return x.GlobalStats
	}
	return nil
}

func (x *StatsReport) GetTopFlows() []*FlowSample {
	if x != nil {
		return x.TopFlows
	}
	return nil
}

func (x *StatsReport) GetSrcIpStats() []*IPStats {
	if x != nil {
		return x.SrcIpStats
	}
	return nil
}

func (x *StatsReport) GetSrcPrefixStats() []*PrefixStatsMsg {
	if x != nil {
		return x.SrcPrefixStats
	}
	return nil
}

func (x *StatsReport) GetSrcIpStatsTruncated() bool {
	if x != nil {
		return x.SrcIpStatsTruncated
	}
	return false
}

func (x *StatsReport) GetTotalActiveSrcIps() uint32 {
	if x != nil {
		return x.TotalActiveSrcIps
	}
	return 0
}

// FlowSample is a single aggregated flow (5-tuple) from one tick.
type FlowSample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcIp         []byte                 `protobuf:"bytes,1,opt,name=src_ip,json=srcIp,proto3" json:"src_ip,omitempty"` // 4 or 16 bytes
	DstIp         []byte                 `protobuf:"bytes,2,opt,name=dst_ip,json=dstIp,proto3" json:"dst_ip,omitempty"`
	SrcPort       uint32                 `protobuf:"varint,3,opt,name=src_port,json=srcPort,proto3" json:"src_port,omitempty"`
	DstPort       uint32                 `protobuf:"varint,4,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`
	Protocol      uint32                 `protobuf:"varint,5,opt,name=protocol,proto3" json:"protocol,omitempty"`                 // 6=TCP, 17=UDP, 1=ICMP
	TcpFlags      uint32                 `protobuf:"varint,6,opt,name=tcp_flags,json=tcpFlags,proto3" json:"tcp_flags,omitempty"` // cumulative OR of all TCP flags
	Packets       uint64                 `protobuf:"varint,7,opt,name=packets,proto3" json:"packets,omitempty"`
	BytesTotal    uint64                 `protobuf:"varint,8,opt,name=bytes_total,json=bytesTotal,proto3" json:"bytes_total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlowSample) Reset() {
	*x = FlowSample{}
	mi := &file_xsight_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowSample) ProtoMessage() {}

func (x *FlowSample) ProtoReflect() protoreflect.Message {
	mi := &file_xsight_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowSample.ProtoReflect.Descriptor instead.
func (*FlowSample) Descriptor() ([]byte, []int) {
	return file_xsight_proto_rawDescGZIP(), []int{3}
}

func (x *FlowSample) GetSrcIp() []byte {
	if x != nil {
		return x.SrcIp
	}
	return nil
}

func (x *FlowSample) GetDstIp() []byte {
	if x != nil {
		return x.DstIp
	}
	return nil
}

func (x *FlowSample) GetSrcPort() uint32 {
	if x != nil {
		return x.SrcPort
	}
	return 0
}

func (x *FlowSample) GetDstPort() uint32 {
	if x != nil {
		return x.DstPort
	}
	return 0
}

func (x *FlowSample) GetProtocol() uint32 {
	if x != nil {
		return x.Protocol
	}
	return 0
}

func (x *FlowSample) GetTcpFlags() uint32 {
	if x != nil {
		return x.TcpFlags
	}
	return 0
}

func (x *FlowSample) GetPackets() uint64 {
	if x != nil {
		return x.Packets
	}
	return 0
}

func (x *FlowSample) GetBytesTotal() uint64 {
	if x != nil {
		return x.BytesTotal
	}
	return 0
}

type IPStats struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	DstIp     []byte                 `protobuf:"bytes,1,opt,name=dst_ip,json=dstIp,proto3" json:"dst_ip,omitempty"` // 4 bytes (IPv4) or 16 bytes (IPv6)
	PktCount  uint64                 `protobuf:"varint,2,opt,name=pkt_count,json=pktCount,proto3" json:"pkt_count,omitempty"`
	ByteCount uint64                 `protobuf:"varint,3,opt,name=byte_count,json=byteCount,proto3" json:"byte_count,omitempty"`
	// Fields 4-8 DEPRECATED — kept for rollout backward compatibility.
	// Controller reads field 20 first; if empty, falls back to these.
	// Will be replaced with 'reserved 4,5,6,7,8' in a future cleanup release.
	//
	// Deprecated: Marked as deprecated in xsight.proto.
	TcpCount uint32 `protobuf:"varint,4,opt,name=tcp_count,json=tcpCount,proto3" json:"tcp_count,omitempty"`
	// Deprecated: Marked as deprecated in xsight.proto.
	TcpSynCount uint32 `protobuf:"varint,5,opt,name=tcp_syn_count,json=tcpSynCount,proto3" json:"tcp_syn_count,omitempty"`
	// Deprecated: Marked as deprecated in xsight.proto.
	UdpCount uint32 `protobuf:"varint,6,opt,name=udp_count,json=udpCount,proto3" json:"udp_count,omitempty"`
	// Deprecated: Marked as deprecated in xsight.proto.
	IcmpCount uint32 `protobuf:"varint,7,opt,name=icmp_count,json=icmpCount,proto3" json:"icmp_count,omitempty"`
	// Deprecated: Marked as deprecated in xsight.proto.
	FragCount         uint32   `protobuf:"varint,8,opt,name=frag_count,json=fragCount,proto3" json:"frag_count,omitempty"`
	SmallPkt          uint32   `protobuf:"varint,9,opt,name=small_pkt,json=smallPkt,proto3" json:"small_pkt,omitempty"`                                      // <128B
	MediumPkt         uint32   `protobuf:"varint,10,opt,name=medium_pkt,json=mediumPkt,proto3" json:"medium_pkt,omitempty"`                                  // 128-512B
	LargePkt          uint32   `protobuf:"varint,11,opt,name=large_pkt,json=largePkt,proto3" json:"large_pkt,omitempty"`                                     // >512B
	DecoderCounts     []uint32 `protobuf:"varint,20,rep,packed,name=decoder_counts,json=decoderCounts,proto3" json:"decoder_counts,omitempty"`               // indexed by shared/decoder constants
	DecoderByteCounts []uint64 `protobuf:"varint,21,rep,packed,name=decoder_byte_counts,json=decoderByteCounts,proto3" json:"decoder_byte_counts,omitempty"` // per-decoder byte counts for BPS thresholds
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *IPStats) Reset() {
	*x = IPStats{}
	mi := &file_xsight_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPStats) ProtoMessage() {}

func (x *IPStats) ProtoReflect() protoreflect.Message {
	mi := &file_xsight_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPStats.ProtoReflect.Descriptor instead.
func (*IPStats) Descriptor() ([]byte, []int) {
	return file_xsight_proto_rawDescGZIP(), []int{4}
}

func (x *IPStats) GetDstIp() []byte {
	if x != nil {
		return x.DstIp
	}
	return nil
}

func (x *IPStats) GetPktCount() uint64 {
	if x != nil {
		return x.PktCount
	}
	return 0
}

func (x *IPStats) GetByteCount() uint64 {
	if x != nil {
		return x.ByteCount
	}
	return 0
}

// Deprecated: Marked as deprecated in xsight.proto.
func (x *IPStats) GetTcpCount() uint32 {
	if x != nil {
		return x.TcpCount
	}
	return 0
}

// Deprecated: Marked as deprecated in xsight.proto.
func (x *IPStats) GetTcpSynCount() uint32 {
	if x != nil {
		return x.TcpSynCount
	}
	return 0
}

// Deprecated: Marked as deprecated in xsight.proto.
func (x *IPStats) GetUdpCount() uint32 {
	if x != nil {
		return x.UdpCount
	}
	return 0
}

// Deprecated: Marked as deprecated in xsight.proto.
func (x *IPStats) GetIcmpCount() uint32 {
	if x != nil {
		return x.IcmpCount
	}
	return 0
}

// Deprecated: Marked as deprecated in xsight.proto.
func (x *IPStats) GetFragCount() uint32 {
	if x != nil {
		return x.FragCount
	}
	return 0
}

func (x *IPStats) GetSmallPkt() uint32 {
	if x != nil {
		return x.SmallPkt
	}
	return 0
}

func (x *IPStats) GetMediumPkt() uint32 {
	if x != nil {
		return x.MediumPkt
	}
	return 0
}

func (x *IPStats) GetLargePkt() uint32 {
	if x != nil {
		return x.LargePkt
	}
	return 0
}

func (x *IPStats) GetDecoderCounts() []uint32 {
	if x != nil {
		return x.DecoderCounts
	}
	return nil
}

func (x *IPStats) GetDecoderByteCounts() []uint64 {
	if x != nil {
		return x.DecoderByteCounts
	}
	return nil
}

type PrefixStatsMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        []byte                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"` // network address (4 or 16 bytes)
	PrefixLen     uint32                 `protobuf:"varint,2,opt,name=prefix_len,json=prefixLen,proto3" json:"prefix_len,omitempty"`
	PktCount      uint64                 `protobuf:"varint,3,opt,name=pkt_count,json=pktCount,proto3" json:"pkt_count,omitempty"`
	ByteCount     uint64                 `protobuf:"varint,4,opt,name=byte_count,json=byteCount,proto3" json:"byte_count,omitempty"`
	ActiveIps     uint32                 `protobuf:"varint,5,opt,name=active_ips,json=activeIps,proto3" json:"active_ips,omitempty"`
	OverflowCount uint32                 `protobuf:"varint,6,opt,name=overflow_count,json=overflowCount,proto3" json:"overflow_count,omitempty"`
	// Fields 7-11 DEPRECATED — same rollout strategy as IPStats.
	//
	// Deprecated: Marked as deprecated in xsight.proto.
	TcpCount uint32 `protobuf:"varint,7,opt,name=tcp_count,json=tcpCount,proto3" json:"tcp_count,omitempty"`
	// Deprecated: Marked as deprecated in xsight.proto.
	TcpSynCount uint32 `protobuf:"varint,8,opt,name=tcp_syn_count,json=tcpSynCount,proto3" json:"tcp_syn_count,omitempty"`
	// Deprecated: Marked as deprecated in xsight.proto.
	UdpCount uint32 `protobuf:"varint,9,opt,name=udp_count,json=udpCount,proto3" json:"udp_count,omitempty"`
	// Deprecated: Marked as deprecated in xsight.proto.
	IcmpCount uint32 `protobuf:"varint,10,opt,name=icmp_count,json=icmpCount,proto3" json:"icmp_count,omitempty"`
	// Deprecated: Marked as deprecated in xsight.proto.
	FragCount         uint32   `protobuf:"varint,11,opt,name=frag_count,json=fragCount,proto3" json:"frag_count,omitempty"`
	DecoderCounts     []uint32 `protobuf:"varint,20,rep,packed,name=decoder_counts,json=decoderCounts,proto3" json:"decoder_counts,omitempty"`               // indexed by shared/decoder constants
	DecoderByteCounts []uint64 `protobuf:"varint,21,rep,packed,name=decoder_byte_counts,json=decoderByteCounts,proto3" json:"decoder_byte_counts,omitempty"` // per-decoder byte counts for BPS thresholds
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PrefixStatsMsg) Reset() {
	*x = PrefixStatsMsg{}
	mi := &file_xsight_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrefixStatsMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrefixStatsMsg) ProtoMessage() {}

func (x *PrefixStatsMsg) ProtoReflect() protoreflect.Message {
	mi := &file_xsight_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrefixStatsMsg.ProtoReflect.Descriptor instead.
func (*PrefixStatsMsg) Descriptor() ([]byte, []int) {
	return file_xsight_proto_rawDescGZIP(), []int{5}
}

func (x *PrefixStatsMsg) GetPrefix() []byte {
	if x != nil {
		return x.Prefix
	}
	return nil
}

func (x *PrefixStatsMsg) GetPrefixLen() uint32 {
	if x != nil {
		return x.PrefixLen
	}
	return 0
}

func (x *PrefixStatsMsg) GetPktCount() uint64 {
	if x != nil {
		return x.PktCount
	}
	return 0
}

func (x *PrefixStatsMsg) GetByteCount() uint64 {
	if x != nil {
		return x.ByteCount
	}
	return 0
}

func (x *PrefixStatsMsg) GetActiveIps() uint32 {
	if x != nil {
		return x.ActiveIps
	}
	return 0
}

func (x *PrefixStatsMsg) GetOverflowCount() uint32 {
	if x != nil {
		return x.OverflowCount
	}
	return 0
}

// Deprecated: Marked as deprecated in xsight.proto.
func (x *PrefixStatsMsg) GetTcpCount() uint32 {
	if x != nil {
		return x.TcpCount
	}
	return 0
}

// Deprecated: Marked as deprecated in xsight.proto.
func (x *PrefixStatsMsg) GetTcpSynCount() uint32 {
	if x != nil {
		return x.TcpSynCount
	}
	return 0
}

// Deprecated: Marked as deprecated in xsight.proto.
func (x *PrefixStatsMsg) GetUdpCount() uint32 {
	if x != nil {
		return x.UdpCount
	}
	return 0
}

// Deprecated: Marked as deprecated in xsight.proto.
func (x *PrefixStatsMsg) GetIcmpCount() uint32 {
	if x != nil {
		return x.IcmpCount
	}
	return 0
}

// Deprecated: Marked as deprecated in xsight.proto.
func (x *PrefixStatsMsg) GetFragCount() uint32 {
	if x != nil {
		return x.FragCount
	}
	return 0
}

func (x *PrefixStatsMsg) GetDecoderCounts() []uint32 {
	if x != nil {
		return x.DecoderCounts
	}
	return nil
}

func (x *PrefixStatsMsg) GetDecoderByteCounts() []uint64 {
	if x != nil {
		return x.DecoderByteCounts
	}
	return nil
}

type GlobalStatsMsg struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TotalPkts         uint64                 `protobuf:"varint,1,opt,name=total_pkts,json=totalPkts,proto3" json:"total_pkts,omitempty"`
	TotalBytes        uint64                 `protobuf:"varint,2,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	MatchedPkts       uint64                 `protobuf:"varint,3,opt,name=matched_pkts,json=matchedPkts,proto3" json:"matched_pkts,omitempty"`
	MatchedBytes      uint64                 `protobuf:"varint,4,opt,name=matched_bytes,json=matchedBytes,proto3" json:"matched_bytes,omitempty"`                          // v2.11: bytes within watch scope (for global ip+bps)
	DecoderCounts     []uint32               `protobuf:"varint,20,rep,packed,name=decoder_counts,json=decoderCounts,proto3" json:"decoder_counts,omitempty"`               // v2.11: per-decoder PPS breakdown (matched only)
	DecoderByteCounts []uint64               `protobuf:"varint,21,rep,packed,name=decoder_byte_counts,json=decoderByteCounts,proto3" json:"decoder_byte_counts,omitempty"` // v2.11: per-decoder BPS breakdown (matched only)
	// v2.11 Phase 2: outbound (src_ip matched) global counters
	SrcMatchedPkts       uint64   `protobuf:"varint,30,opt,name=src_matched_pkts,json=srcMatchedPkts,proto3" json:"src_matched_pkts,omitempty"`
	SrcMatchedBytes      uint64   `protobuf:"varint,31,opt,name=src_matched_bytes,json=srcMatchedBytes,proto3" json:"src_matched_bytes,omitempty"`
	SrcDecoderCounts     []uint32 `protobuf:"varint,32,rep,packed,name=src_decoder_counts,json=srcDecoderCounts,proto3" json:"src_decoder_counts,omitempty"`
	SrcDecoderByteCounts []uint64 `protobuf:"varint,33,rep,packed,name=src_decoder_byte_counts,json=srcDecoderByteCounts,proto3" json:"src_decoder_byte_counts,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GlobalStatsMsg) Reset() {
	*x = GlobalStatsMsg{}
	mi := &file_xsight_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalStatsMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalStatsMsg) ProtoMessage() {}

func (x *GlobalStatsMsg) ProtoReflect() protoreflect.Message {
	mi := &file_xsight_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalStatsMsg.ProtoReflect.Descriptor instead.
func (*GlobalStatsMsg) Descriptor() ([]byte, []int) {
	return file_xsight_proto_rawDescGZIP(), []int{6}
}

func (x *GlobalStatsMsg) GetTotalPkts() uint64 {
	if x != nil {
		return x.TotalPkts
	}
	return 0
}

func (x *GlobalStatsMsg) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *GlobalStatsMsg) GetMatchedPkts() uint64 {
	if x != nil {
		return x.MatchedPkts
	}
	return 0
}

func (x *GlobalStatsMsg) GetMatchedBytes() uint64 {
	if x != nil {
		return x.MatchedBytes
	}
	return 0
}

func (x *GlobalStatsMsg) GetDecoderCounts() []uint32 {
	if x != nil {
		return x.DecoderCounts
	}
	return nil
}

func (x *GlobalStatsMsg) GetDecoderByteCounts() []uint64 {
	if x != nil {
		return x.DecoderByteCounts
	}
	return nil
}

func (x *GlobalStatsMsg) GetSrcMatchedPkts() uint64 {
	if x != nil {
		return x.SrcMatchedPkts
	}
	return 0
}

func (x *GlobalStatsMsg) GetSrcMatchedBytes() uint64 {
	if x != nil {
		return x.SrcMatchedBytes
	}
	return 0
}

func (x *GlobalStatsMsg) GetSrcDecoderCounts() []uint32 {
	if x != nil {
		return x.SrcDecoderCounts
	}
	return nil
}

func (x *GlobalStatsMsg) GetSrcDecoderByteCounts() []uint64 {
	if x != nil {
		return x.SrcDecoderByteCounts
	}
	return nil
}

type NodeHealth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "healthy" | "degraded" | "unhealthy"
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeHealth) Reset() {
	*x = NodeHealth{}
	mi := &file_xsight_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeHealth) ProtoMessage() {}

func (x *NodeHealth) ProtoReflect() protoreflect.Message {
	mi := &file_xsight_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeHealth.ProtoReflect.Descriptor instead.
func (*NodeHealth) Descriptor() ([]byte, []int) {
	return file_xsight_proto_rawDescGZIP(), []int{7}
}

func (x *NodeHealth) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NodeHealth) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SamplingMetrics struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RingFillRatio       float32                `protobuf:"fixed32,1,opt,name=ring_fill_ratio,json=ringFillRatio,proto3" json:"ring_fill_ratio,omitempty"`
	DroppedKernel       uint64                 `protobuf:"varint,2,opt,name=dropped_kernel,json=droppedKernel,proto3" json:"dropped_kernel,omitempty"`
	DroppedUser         uint64                 `protobuf:"varint,3,opt,name=dropped_user,json=droppedUser,proto3" json:"dropped_user,omitempty"`
	DecodeError         uint64                 `protobuf:"varint,4,opt,name=decode_error,json=decodeError,proto3" json:"decode_error,omitempty"`
	BatchSendLatencyMs  float32                `protobuf:"fixed32,5,opt,name=batch_send_latency_ms,json=batchSendLatencyMs,proto3" json:"batch_send_latency_ms,omitempty"`
	EffectiveSampleRate float32                `protobuf:"fixed32,6,opt,name=effective_sample_rate,json=effectiveSampleRate,proto3" json:"effective_sample_rate,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SamplingMetrics) Reset() {
	*x = SamplingMetrics{}
	mi := &file_xsight_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SamplingMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SamplingMetrics) ProtoMessage() {}

func (x *SamplingMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_xsight_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SamplingMetrics.ProtoReflect.Descriptor instead.
func (*SamplingMetrics) Descriptor() ([]byte, []int) {
	return file_xsight_proto_rawDescGZIP(), []int{8}
}

func (x *SamplingMetrics) GetRingFillRatio() float32 {
	if x != nil {
		return x.RingFillRatio
	}
	return 0
}

func (x *SamplingMetrics) GetDroppedKernel() uint64 {
	if x != nil {
		return x.DroppedKernel
	}
	return 0
}

func (x *SamplingMetrics) GetDroppedUser() uint64 {
	if x != nil {
		return x.DroppedUser
	}
	return 0
}

func (x *SamplingMetrics) GetDecodeError() uint64 {
	if x != nil {
		return x.DecodeError
	}
	return 0
}

func (x *SamplingMetrics) GetBatchSendLatencyMs() float32 {
	if x != nil {
		return x.BatchSendLatencyMs
	}
	return 0
}

func (x *SamplingMetrics) GetEffectiveSampleRate() float32 {
	if x != nil {
		return x.EffectiveSampleRate
	}
	return 0
}

type SampleBatch struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	NodeId             string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	InterfaceName      string                 `protobuf:"bytes,2,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	UpstreamSampleRate uint32                 `protobuf:"varint,3,opt,name=upstream_sample_rate,json=upstreamSampleRate,proto3" json:"upstream_sample_rate,omitempty"`
	LocalSampleRate    uint32                 `protobuf:"varint,4,opt,name=local_sample_rate,json=localSampleRate,proto3" json:"local_sample_rate,omitempty"`
	Timestamp          int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Samples            []*PacketSample        `protobuf:"bytes,6,rep,name=samples,proto3" json:"samples,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SampleBatch) Reset() {
	*x = SampleBatch{}
	mi := &file_xsight_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SampleBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SampleBatch) ProtoMessage() {}

func (x *SampleBatch) ProtoReflect() protoreflect.Message {
	mi := &file_xsight_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SampleBatch.ProtoReflect.Descriptor instead.
func (*SampleBatch) Descriptor() ([]byte, []int) {
	return file_xsight_proto_rawDescGZIP(), []int{9}
}

func (x *SampleBatch) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *SampleBatch) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *SampleBatch) GetUpstreamSampleRate() uint32 {
	if x != nil {
		return x.UpstreamSampleRate
	}
	return 0
}

func (x *SampleBatch) GetLocalSampleRate() uint32 {
	if x != nil {
		return x.LocalSampleRate
	}
	return 0
}

func (x *SampleBatch) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SampleBatch) GetSamples() []*PacketSample {
	if x != nil {
		return x.Samples
	}
	return nil
}

type PacketSample struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RawHeader      []byte                 `protobuf:"bytes,1,opt,name=raw_header,json=rawHeader,proto3" json:"raw_header,omitempty"`
	SrcIp          []byte                 `protobuf:"bytes,2,opt,name=src_ip,json=srcIp,proto3" json:"src_ip,omitempty"`
	DstIp          []byte                 `protobuf:"bytes,3,opt,name=dst_ip,json=dstIp,proto3" json:"dst_ip,omitempty"`
	IpProtocol     uint32                 `protobuf:"varint,4,opt,name=ip_protocol,json=ipProtocol,proto3" json:"ip_protocol,omitempty"`
	SrcPort        uint32                 `protobuf:"varint,5,opt,name=src_port,json=srcPort,proto3" json:"src_port,omitempty"`
	DstPort        uint32                 `protobuf:"varint,6,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`
	PacketLength   uint32                 `protobuf:"varint,7,opt,name=packet_length,json=packetLength,proto3" json:"packet_length,omitempty"`
	TcpFlags       uint32                 `protobuf:"varint,8,opt,name=tcp_flags,json=tcpFlags,proto3" json:"tcp_flags,omitempty"`
	IpTtl          uint32                 `protobuf:"varint,9,opt,name=ip_ttl,json=ipTtl,proto3" json:"ip_ttl,omitempty"`
	FragmentOffset uint32                 `protobuf:"varint,10,opt,name=fragment_offset,json=fragmentOffset,proto3" json:"fragment_offset,omitempty"`
	IcmpType       uint32                 `protobuf:"varint,11,opt,name=icmp_type,json=icmpType,proto3" json:"icmp_type,omitempty"`
	IcmpCode       uint32                 `protobuf:"varint,12,opt,name=icmp_code,json=icmpCode,proto3" json:"icmp_code,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PacketSample) Reset() {
	*x = PacketSample{}
	mi := &file_xsight_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PacketSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketSample) ProtoMessage() {}

func (x *PacketSample) ProtoReflect() protoreflect.Message {
	mi := &file_xsight_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketSample.ProtoReflect.Descriptor instead.
func (*PacketSample) Descriptor() ([]byte, []int) {
	return file_xsight_proto_rawDescGZIP(), []int{10}
}

func (x *PacketSample) GetRawHeader() []byte {
	if x != nil {
		return x.RawHeader
	}
	return nil
}

func (x *PacketSample) GetSrcIp() []byte {
	if x != nil {
		return x.SrcIp
	}
	return nil
}

func (x *PacketSample) GetDstIp() []byte {
	if x != nil {
		return x.DstIp
	}
	return nil
}

func (x *PacketSample) GetIpProtocol() uint32 {
	if x != nil {
		return x.IpProtocol
	}
	return 0
}

func (x *PacketSample) GetSrcPort() uint32 {
	if x != nil {
		return x.SrcPort
	}
	return 0
}

func (x *PacketSample) GetDstPort() uint32 {
	if x != nil {
		return x.DstPort
	}
	return 0
}

func (x *PacketSample) GetPacketLength() uint32 {
	if x != nil {
		return x.PacketLength
	}
	return 0
}

func (x *PacketSample) GetTcpFlags() uint32 {
	if x != nil {
		return x.TcpFlags
	}
	return 0
}

func (x *PacketSample) GetIpTtl() uint32 {
	if x != nil {
		return x.IpTtl
	}
	return 0
}

func (x *PacketSample) GetFragmentOffset() uint32 {
	if x != nil {
		return x.FragmentOffset
	}
	return 0
}

func (x *PacketSample) GetIcmpType() uint32 {
	if x != nil {
		return x.IcmpType
	}
	return 0
}

func (x *PacketSample) GetIcmpCode() uint32 {
	if x != nil {
		return x.IcmpCode
	}
	return 0
}

type CriticalEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	InterfaceName string                 `protobuf:"bytes,2,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	DstIp         []byte                 `protobuf:"bytes,4,opt,name=dst_ip,json=dstIp,proto3" json:"dst_ip,omitempty"`
	EventType     string                 `protobuf:"bytes,5,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`                                                         // e.g. "hard_threshold_exceeded"
	Counters      map[string]uint64      `protobuf:"bytes,6,rep,name=counters,proto3" json:"counters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // snapshot at trigger time
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CriticalEvent) Reset() {
	*x = CriticalEvent{}
	mi := &file_xsight_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CriticalEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CriticalEvent) ProtoMessage() {}

func (x *CriticalEvent) ProtoReflect() protoreflect.Message {
	mi := &file_xsight_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CriticalEvent.ProtoReflect.Descriptor instead.
func (*CriticalEvent) Descriptor() ([]byte, []int) {
	return file_xsight_proto_rawDescGZIP(), []int{11}
}

func (x *CriticalEvent) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *CriticalEvent) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *CriticalEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *CriticalEvent) GetDstIp() []byte {
	if x != nil {
		return x.DstIp
	}
	return nil
}

func (x *CriticalEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *CriticalEvent) GetCounters() map[string]uint64 {
	if x != nil {
		return x.Counters
	}
	return nil
}

type ControlMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ControlMessage_ConfigPush
	//	*ControlMessage_ConfigAck
	Payload       isControlMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlMessage) Reset() {
	*x = ControlMessage{}
	mi := &file_xsight_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMessage) ProtoMessage() {}

func (x *ControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_xsight_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMessage.ProtoReflect.Descriptor instead.
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return file_xsight_proto_rawDescGZIP(), []int{12}
}

func (x *ControlMessage) GetPayload() isControlMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ControlMessage) GetConfigPush() *ConfigPush {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_ConfigPush); ok {
			return x.ConfigPush
		}
	}
	return nil
}

func (x *ControlMessage) GetConfigAck() *ConfigAck {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_ConfigAck); ok {
			return x.ConfigAck
		}
	}
	return nil
}

type isControlMessage_Payload interface {
	isControlMessage_Payload()
}

type ControlMessage_ConfigPush struct {
	ConfigPush *ConfigPush `protobuf:"bytes,1,opt,name=config_push,json=configPush,proto3,oneof"`
}

type ControlMessage_ConfigAck struct {
	ConfigAck *ConfigAck `protobuf:"bytes,2,opt,name=config_ack,json=configAck,proto3,oneof"`
}

func (*ControlMessage_ConfigPush) isControlMessage_Payload() {}

func (*ControlMessage_ConfigAck) isControlMessage_Payload() {}

type ConfigPush struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	WatchConfig            *WatchConfig           `protobuf:"bytes,1,opt,name=watch_config,json=watchConfig,proto3" json:"watch_config,omitempty"`
	DeliveryVersionCurrent uint64                 `protobuf:"varint,2,opt,name=delivery_version_current,json=deliveryVersionCurrent,proto3" json:"delivery_version_current,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ConfigPush) Reset() {
	*x = ConfigPush{}
	mi := &file_xsight_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigPush) ProtoMessage() {}

func (x *ConfigPush) ProtoReflect() protoreflect.Message {
	mi := &file_xsight_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigPush.ProtoReflect.Descriptor instead.
func (*ConfigPush) Descriptor() ([]byte, []int) {
	return file_xsight_proto_rawDescGZIP(), []int{13}
}

func (x *ConfigPush) GetWatchConfig() *WatchConfig {
	if x != nil {
		return x.WatchConfig
	}
	return nil
}

func (x *ConfigPush) GetDeliveryVersionCurrent() uint64 {
	if x != nil {
		return x.DeliveryVersionCurrent
	}
	return 0
}

type ConfigAck struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	DeliveryVersionApplied uint64                 `protobuf:"varint,1,opt,name=delivery_version_applied,json=deliveryVersionApplied,proto3" json:"delivery_version_applied,omitempty"`
	Success                bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage           string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ConfigAck) Reset() {
	*x = ConfigAck{}
	mi := &file_xsight_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigAck) ProtoMessage() {}

func (x *ConfigAck) ProtoReflect() protoreflect.Message {
	mi := &file_xsight_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigAck.ProtoReflect.Descriptor instead.
func (*ConfigAck) Descriptor() ([]byte, []int) {
	return file_xsight_proto_rawDescGZIP(), []int{14}
}

func (x *ConfigAck) GetDeliveryVersionApplied() uint64 {
	if x != nil {
		return x.DeliveryVersionApplied
	}
	return 0
}

func (x *ConfigAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfigAck) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type WatchConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Prefixes       []*WatchPrefix         `protobuf:"bytes,1,rep,name=prefixes,proto3" json:"prefixes,omitempty"`
	HardThresholds *HardThresholds        `protobuf:"bytes,2,opt,name=hard_thresholds,json=hardThresholds,proto3" json:"hard_thresholds,omitempty"`
	// v3.0: flow mode config (ignored by xdp nodes, protobuf backward compatible)
	FlowListeners []*FlowListenerConfig `protobuf:"bytes,3,rep,name=flow_listeners,json=flowListeners,proto3" json:"flow_listeners,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchConfig) Reset() {
	*x = WatchConfig{}
	mi := &file_xsight_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchConfig) ProtoMessage() {}

func (x *WatchConfig) ProtoReflect() protoreflect.Message {
	mi := &file_xsight_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchConfig.ProtoReflect.Descriptor instead.
func (*WatchConfig) Descriptor() ([]byte, []int) {
	return file_xsight_proto_rawDescGZIP(), []int{15}
}

func (x *WatchConfig) GetPrefixes() []*WatchPrefix {
	if x != nil {
		return x.Prefixes
	}
	return nil
}

func (x *WatchConfig) GetHardThresholds() *HardThresholds {
	if x != nil {
		return x.HardThresholds
	}
	return nil
}

func (x *WatchConfig) GetFlowListeners() []*FlowListenerConfig {
	if x != nil {
		return x.FlowListeners
	}
	return nil
}

// v3.0: Flow listener + source config pushed to Flow Nodes
type FlowListenerConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListenAddress string                 `protobuf:"bytes,1,opt,name=listen_address,json=listenAddress,proto3" json:"listen_address,omitempty"` // ":6343", ":2055"
	ProtocolMode  string                 `protobuf:"bytes,2,opt,name=protocol_mode,json=protocolMode,proto3" json:"protocol_mode,omitempty"`    // "auto" | "sflow" | "netflow" | "ipfix"
	Sources       []*FlowSourceConfig    `protobuf:"bytes,3,rep,name=sources,proto3" json:"sources,omitempty"`
	Enabled       bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlowListenerConfig) Reset() {
	*x = FlowListenerConfig{}
	mi := &file_xsight_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowListenerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowListenerConfig) ProtoMessage() {}

func (x *FlowListenerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_xsight_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowListenerConfig.ProtoReflect.Descriptor instead.
func (*FlowListenerConfig) Descriptor() ([]byte, []int) {
	return file_xsight_proto_rawDescGZIP(), []int{16}
}

func (x *FlowListenerConfig) GetListenAddress() string {
	if x != nil {
		return x.ListenAddress
	}
	return ""
}

func (x *FlowListenerConfig) GetProtocolMode() string {
	if x != nil {
		return x.ProtocolMode
	}
	return ""
}

func (x *FlowListenerConfig) GetSources() []*FlowSourceConfig {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *FlowListenerConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type FlowSourceConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceIp      string                 `protobuf:"bytes,1,opt,name=device_ip,json=deviceIp,proto3" json:"device_ip,omitempty"`        // exporter IP (matched against UDP src)
	SampleMode    string                 `protobuf:"bytes,2,opt,name=sample_mode,json=sampleMode,proto3" json:"sample_mode,omitempty"`  // "auto" | "force" | "none"
	SampleRate    int32                  `protobuf:"varint,3,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"` // force mode override value
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`                                // display name
	Enabled       bool                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlowSourceConfig) Reset() {
	*x = FlowSourceConfig{}
	mi := &file_xsight_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowSourceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowSourceConfig) ProtoMessage() {}

func (x *FlowSourceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_xsight_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowSourceConfig.ProtoReflect.Descriptor instead.
func (*FlowSourceConfig) Descriptor() ([]byte, []int) {
	return file_xsight_proto_rawDescGZIP(), []int{17}
}

func (x *FlowSourceConfig) GetDeviceIp() string {
	if x != nil {
		return x.DeviceIp
	}
	return ""
}

func (x *FlowSourceConfig) GetSampleMode() string {
	if x != nil {
		return x.SampleMode
	}
	return ""
}

func (x *FlowSourceConfig) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *FlowSourceConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FlowSourceConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type WatchPrefix struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        []byte                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"` // network address
	PrefixLen     uint32                 `protobuf:"varint,2,opt,name=prefix_len,json=prefixLen,proto3" json:"prefix_len,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"` // human-readable label
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchPrefix) Reset() {
	*x = WatchPrefix{}
	mi := &file_xsight_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchPrefix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchPrefix) ProtoMessage() {}

func (x *WatchPrefix) ProtoReflect() protoreflect.Message {
	mi := &file_xsight_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchPrefix.ProtoReflect.Descriptor instead.
func (*WatchPrefix) Descriptor() ([]byte, []int) {
	return file_xsight_proto_rawDescGZIP(), []int{18}
}

func (x *WatchPrefix) GetPrefix() []byte {
	if x != nil {
		return x.Prefix
	}
	return nil
}

func (x *WatchPrefix) GetPrefixLen() uint32 {
	if x != nil {
		return x.PrefixLen
	}
	return 0
}

func (x *WatchPrefix) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type HardThresholds struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pps           uint64                 `protobuf:"varint,1,opt,name=pps,proto3" json:"pps,omitempty"` // per-IP packets/sec threshold
	Bps           uint64                 `protobuf:"varint,2,opt,name=bps,proto3" json:"bps,omitempty"` // per-IP bits/sec threshold
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HardThresholds) Reset() {
	*x = HardThresholds{}
	mi := &file_xsight_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HardThresholds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HardThresholds) ProtoMessage() {}

func (x *HardThresholds) ProtoReflect() protoreflect.Message {
	mi := &file_xsight_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HardThresholds.ProtoReflect.Descriptor instead.
func (*HardThresholds) Descriptor() ([]byte, []int) {
	return file_xsight_proto_rawDescGZIP(), []int{19}
}

func (x *HardThresholds) GetPps() uint64 {
	if x != nil {
		return x.Pps
	}
	return 0
}

func (x *HardThresholds) GetBps() uint64 {
	if x != nil {
		return x.Bps
	}
	return 0
}

var File_xsight_proto protoreflect.FileDescriptor

const file_xsight_proto_rawDesc = "" +
	"\n" +
	"\fxsight.proto\x12\x06xsight\x1a\x1bgoogle/protobuf/empty.proto\"\xd4\x01\n" +
	"\rNodeHandshake\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\x12\x1e\n" +
	"\n" +
	"interfaces\x18\x03 \x03(\tR\n" +
	"interfaces\x12#\n" +
	"\ragent_version\x18\x04 \x01(\tR\fagentVersion\x128\n" +
	"\x18delivery_version_applied\x18\x05 \x01(\x04R\x16deliveryVersionApplied\x12\x12\n" +
	"\x04mode\x18\x06 \x01(\tR\x04mode\"\xc6\x01\n" +
	"\x11HandshakeResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12#\n" +
	"\rreject_reason\x18\x02 \x01(\tR\frejectReason\x126\n" +
	"\fwatch_config\x18\x03 \x01(\v2\x13.xsight.WatchConfigR\vwatchConfig\x128\n" +
	"\x18delivery_version_current\x18\x04 \x01(\x04R\x16deliveryVersionCurrent\"\xe0\x06\n" +
	"\vStatsReport\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12%\n" +
	"\x0einterface_name\x18\x02 \x01(\tR\rinterfaceName\x120\n" +
	"\x14upstream_sample_rate\x18\x03 \x01(\rR\x12upstreamSampleRate\x12*\n" +
	"\x11local_sample_rate\x18\x04 \x01(\rR\x0flocalSampleRate\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12*\n" +
	"\bip_stats\x18\x06 \x03(\v2\x0f.xsight.IPStatsR\aipStats\x129\n" +
	"\fprefix_stats\x18\a \x03(\v2\x16.xsight.PrefixStatsMsgR\vprefixStats\x12*\n" +
	"\x06health\x18\b \x01(\v2\x12.xsight.NodeHealthR\x06health\x12B\n" +
	"\x10sampling_metrics\x18\t \x01(\v2\x17.xsight.SamplingMetricsR\x0fsamplingMetrics\x12\x1f\n" +
	"\vgap_seconds\x18\n" +
	" \x01(\rR\n" +
	"gapSeconds\x12,\n" +
	"\x12ip_stats_truncated\x18\v \x01(\bR\x10ipStatsTruncated\x12(\n" +
	"\x10total_active_ips\x18\f \x01(\rR\x0etotalActiveIps\x129\n" +
	"\fglobal_stats\x18\r \x01(\v2\x16.xsight.GlobalStatsMsgR\vglobalStats\x12/\n" +
	"\ttop_flows\x18\x14 \x03(\v2\x12.xsight.FlowSampleR\btopFlows\x121\n" +
	"\fsrc_ip_stats\x18\x1e \x03(\v2\x0f.xsight.IPStatsR\n" +
	"srcIpStats\x12@\n" +
	"\x10src_prefix_stats\x18\x1f \x03(\v2\x16.xsight.PrefixStatsMsgR\x0esrcPrefixStats\x123\n" +
	"\x16src_ip_stats_truncated\x18  \x01(\bR\x13srcIpStatsTruncated\x12/\n" +
	"\x14total_active_src_ips\x18! \x01(\rR\x11totalActiveSrcIps\"\xe4\x01\n" +
	"\n" +
	"FlowSample\x12\x15\n" +
	"\x06src_ip\x18\x01 \x01(\fR\x05srcIp\x12\x15\n" +
	"\x06dst_ip\x18\x02 \x01(\fR\x05dstIp\x12\x19\n" +
	"\bsrc_port\x18\x03 \x01(\rR\asrcPort\x12\x19\n" +
	"\bdst_port\x18\x04 \x01(\rR\adstPort\x12\x1a\n" +
	"\bprotocol\x18\x05 \x01(\rR\bprotocol\x12\x1b\n" +
	"\ttcp_flags\x18\x06 \x01(\rR\btcpFlags\x12\x18\n" +
	"\apackets\x18\a \x01(\x04R\apackets\x12\x1f\n" +
	"\vbytes_total\x18\b \x01(\x04R\n" +
	"bytesTotal\"\xbc\x03\n" +
	"\aIPStats\x12\x15\n" +
	"\x06dst_ip\x18\x01 \x01(\fR\x05dstIp\x12\x1b\n" +
	"\tpkt_count\x18\x02 \x01(\x04R\bpktCount\x12\x1d\n" +
	"\n" +
	"byte_count\x18\x03 \x01(\x04R\tbyteCount\x12\x1f\n" +
	"\ttcp_count\x18\x04 \x01(\rB\x02\x18\x01R\btcpCount\x12&\n" +
	"\rtcp_syn_count\x18\x05 \x01(\rB\x02\x18\x01R\vtcpSynCount\x12\x1f\n" +
	"\tudp_count\x18\x06 \x01(\rB\x02\x18\x01R\budpCount\x12!\n" +
	"\n" +
	"icmp_count\x18\a \x01(\rB\x02\x18\x01R\ticmpCount\x12!\n" +
	"\n" +
	"frag_count\x18\b \x01(\rB\x02\x18\x01R\tfragCount\x12\x1b\n" +
	"\tsmall_pkt\x18\t \x01(\rR\bsmallPkt\x12\x1d\n" +
	"\n" +
	"medium_pkt\x18\n" +
	" \x01(\rR\tmediumPkt\x12\x1b\n" +
	"\tlarge_pkt\x18\v \x01(\rR\blargePkt\x12%\n" +
	"\x0edecoder_counts\x18\x14 \x03(\rR\rdecoderCounts\x12.\n" +
	"\x13decoder_byte_counts\x18\x15 \x03(\x04R\x11decoderByteCounts\"\xd0\x03\n" +
	"\x0ePrefixStatsMsg\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\fR\x06prefix\x12\x1d\n" +
	"\n" +
	"prefix_len\x18\x02 \x01(\rR\tprefixLen\x12\x1b\n" +
	"\tpkt_count\x18\x03 \x01(\x04R\bpktCount\x12\x1d\n" +
	"\n" +
	"byte_count\x18\x04 \x01(\x04R\tbyteCount\x12\x1d\n" +
	"\n" +
	"active_ips\x18\x05 \x01(\rR\tactiveIps\x12%\n" +
	"\x0eoverflow_count\x18\x06 \x01(\rR\roverflowCount\x12\x1f\n" +
	"\ttcp_count\x18\a \x01(\rB\x02\x18\x01R\btcpCount\x12&\n" +
	"\rtcp_syn_count\x18\b \x01(\rB\x02\x18\x01R\vtcpSynCount\x12\x1f\n" +
	"\tudp_count\x18\t \x01(\rB\x02\x18\x01R\budpCount\x12!\n" +
	"\n" +
	"icmp_count\x18\n" +
	" \x01(\rB\x02\x18\x01R\ticmpCount\x12!\n" +
	"\n" +
	"frag_count\x18\v \x01(\rB\x02\x18\x01R\tfragCount\x12%\n" +
	"\x0edecoder_counts\x18\x14 \x03(\rR\rdecoderCounts\x12.\n" +
	"\x13decoder_byte_counts\x18\x15 \x03(\x04R\x11decoderByteCounts\"\xaa\x03\n" +
	"\x0eGlobalStatsMsg\x12\x1d\n" +
	"\n" +
	"total_pkts\x18\x01 \x01(\x04R\ttotalPkts\x12\x1f\n" +
	"\vtotal_bytes\x18\x02 \x01(\x04R\n" +
	"totalBytes\x12!\n" +
	"\fmatched_pkts\x18\x03 \x01(\x04R\vmatchedPkts\x12#\n" +
	"\rmatched_bytes\x18\x04 \x01(\x04R\fmatchedBytes\x12%\n" +
	"\x0edecoder_counts\x18\x14 \x03(\rR\rdecoderCounts\x12.\n" +
	"\x13decoder_byte_counts\x18\x15 \x03(\x04R\x11decoderByteCounts\x12(\n" +
	"\x10src_matched_pkts\x18\x1e \x01(\x04R\x0esrcMatchedPkts\x12*\n" +
	"\x11src_matched_bytes\x18\x1f \x01(\x04R\x0fsrcMatchedBytes\x12,\n" +
	"\x12src_decoder_counts\x18  \x03(\rR\x10srcDecoderCounts\x125\n" +
	"\x17src_decoder_byte_counts\x18! \x03(\x04R\x14srcDecoderByteCounts\">\n" +
	"\n" +
	"NodeHealth\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x8d\x02\n" +
	"\x0fSamplingMetrics\x12&\n" +
	"\x0fring_fill_ratio\x18\x01 \x01(\x02R\rringFillRatio\x12%\n" +
	"\x0edropped_kernel\x18\x02 \x01(\x04R\rdroppedKernel\x12!\n" +
	"\fdropped_user\x18\x03 \x01(\x04R\vdroppedUser\x12!\n" +
	"\fdecode_error\x18\x04 \x01(\x04R\vdecodeError\x121\n" +
	"\x15batch_send_latency_ms\x18\x05 \x01(\x02R\x12batchSendLatencyMs\x122\n" +
	"\x15effective_sample_rate\x18\x06 \x01(\x02R\x13effectiveSampleRate\"\xf9\x01\n" +
	"\vSampleBatch\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12%\n" +
	"\x0einterface_name\x18\x02 \x01(\tR\rinterfaceName\x120\n" +
	"\x14upstream_sample_rate\x18\x03 \x01(\rR\x12upstreamSampleRate\x12*\n" +
	"\x11local_sample_rate\x18\x04 \x01(\rR\x0flocalSampleRate\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12.\n" +
	"\asamples\x18\x06 \x03(\v2\x14.xsight.PacketSampleR\asamples\"\xee\x02\n" +
	"\fPacketSample\x12\x1d\n" +
	"\n" +
	"raw_header\x18\x01 \x01(\fR\trawHeader\x12\x15\n" +
	"\x06src_ip\x18\x02 \x01(\fR\x05srcIp\x12\x15\n" +
	"\x06dst_ip\x18\x03 \x01(\fR\x05dstIp\x12\x1f\n" +
	"\vip_protocol\x18\x04 \x01(\rR\n" +
	"ipProtocol\x12\x19\n" +
	"\bsrc_port\x18\x05 \x01(\rR\asrcPort\x12\x19\n" +
	"\bdst_port\x18\x06 \x01(\rR\adstPort\x12#\n" +
	"\rpacket_length\x18\a \x01(\rR\fpacketLength\x12\x1b\n" +
	"\ttcp_flags\x18\b \x01(\rR\btcpFlags\x12\x15\n" +
	"\x06ip_ttl\x18\t \x01(\rR\x05ipTtl\x12'\n" +
	"\x0ffragment_offset\x18\n" +
	" \x01(\rR\x0efragmentOffset\x12\x1b\n" +
	"\ticmp_type\x18\v \x01(\rR\bicmpType\x12\x1b\n" +
	"\ticmp_code\x18\f \x01(\rR\bicmpCode\"\xa1\x02\n" +
	"\rCriticalEvent\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12%\n" +
	"\x0einterface_name\x18\x02 \x01(\tR\rinterfaceName\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x15\n" +
	"\x06dst_ip\x18\x04 \x01(\fR\x05dstIp\x12\x1d\n" +
	"\n" +
	"event_type\x18\x05 \x01(\tR\teventType\x12?\n" +
	"\bcounters\x18\x06 \x03(\v2#.xsight.CriticalEvent.CountersEntryR\bcounters\x1a;\n" +
	"\rCountersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"\x86\x01\n" +
	"\x0eControlMessage\x125\n" +
	"\vconfig_push\x18\x01 \x01(\v2\x12.xsight.ConfigPushH\x00R\n" +
	"configPush\x122\n" +
	"\n" +
	"config_ack\x18\x02 \x01(\v2\x11.xsight.ConfigAckH\x00R\tconfigAckB\t\n" +
	"\apayload\"~\n" +
	"\n" +
	"ConfigPush\x126\n" +
	"\fwatch_config\x18\x01 \x01(\v2\x13.xsight.WatchConfigR\vwatchConfig\x128\n" +
	"\x18delivery_version_current\x18\x02 \x01(\x04R\x16deliveryVersionCurrent\"\x84\x01\n" +
	"\tConfigAck\x128\n" +
	"\x18delivery_version_applied\x18\x01 \x01(\x04R\x16deliveryVersionApplied\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\xc2\x01\n" +
	"\vWatchConfig\x12/\n" +
	"\bprefixes\x18\x01 \x03(\v2\x13.xsight.WatchPrefixR\bprefixes\x12?\n" +
	"\x0fhard_thresholds\x18\x02 \x01(\v2\x16.xsight.HardThresholdsR\x0ehardThresholds\x12A\n" +
	"\x0eflow_listeners\x18\x03 \x03(\v2\x1a.xsight.FlowListenerConfigR\rflowListeners\"\xae\x01\n" +
	"\x12FlowListenerConfig\x12%\n" +
	"\x0elisten_address\x18\x01 \x01(\tR\rlistenAddress\x12#\n" +
	"\rprotocol_mode\x18\x02 \x01(\tR\fprotocolMode\x122\n" +
	"\asources\x18\x03 \x03(\v2\x18.xsight.FlowSourceConfigR\asources\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\"\x9f\x01\n" +
	"\x10FlowSourceConfig\x12\x1b\n" +
	"\tdevice_ip\x18\x01 \x01(\tR\bdeviceIp\x12\x1f\n" +
	"\vsample_mode\x18\x02 \x01(\tR\n" +
	"sampleMode\x12\x1f\n" +
	"\vsample_rate\x18\x03 \x01(\x05R\n" +
	"sampleRate\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\"X\n" +
	"\vWatchPrefix\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\fR\x06prefix\x12\x1d\n" +
	"\n" +
	"prefix_len\x18\x02 \x01(\rR\tprefixLen\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"4\n" +
	"\x0eHardThresholds\x12\x10\n" +
	"\x03pps\x18\x01 \x01(\x04R\x03pps\x12\x10\n" +
	"\x03bps\x18\x02 \x01(\x04R\x03bps2\xd8\x02\n" +
	"\rXSightService\x12=\n" +
	"\tHandshake\x12\x15.xsight.NodeHandshake\x1a\x19.xsight.HandshakeResponse\x12<\n" +
	"\vStatsStream\x12\x13.xsight.StatsReport\x1a\x16.google.protobuf.Empty(\x01\x12=\n" +
	"\fSampleStream\x12\x13.xsight.SampleBatch\x1a\x16.google.protobuf.Empty(\x01\x12F\n" +
	"\x13CriticalEventStream\x12\x15.xsight.CriticalEvent\x1a\x16.google.protobuf.Empty(\x01\x12C\n" +
	"\rControlStream\x12\x16.xsight.ControlMessage\x1a\x16.xsight.ControlMessage(\x010\x01B3Z1github.com/littlewolf9527/xsight/node/internal/pbb\x06proto3"

var (
	file_xsight_proto_rawDescOnce sync.Once
	file_xsight_proto_rawDescData []byte
)

func file_xsight_proto_rawDescGZIP() []byte {
	file_xsight_proto_rawDescOnce.Do(func() {
		file_xsight_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xsight_proto_rawDesc), len(file_xsight_proto_rawDesc)))
	})
	return file_xsight_proto_rawDescData
}

var file_xsight_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_xsight_proto_goTypes = []any{
	(*NodeHandshake)(nil),      // 0: xsight.NodeHandshake
	(*HandshakeResponse)(nil),  // 1: xsight.HandshakeResponse
	(*StatsReport)(nil),        // 2: xsight.StatsReport
	(*FlowSample)(nil),         // 3: xsight.FlowSample
	(*IPStats)(nil),            // 4: xsight.IPStats
	(*PrefixStatsMsg)(nil),     // 5: xsight.PrefixStatsMsg
	(*GlobalStatsMsg)(nil),     // 6: xsight.GlobalStatsMsg
	(*NodeHealth)(nil),         // 7: xsight.NodeHealth
	(*SamplingMetrics)(nil),    // 8: xsight.SamplingMetrics
	(*SampleBatch)(nil),        // 9: xsight.SampleBatch
	(*PacketSample)(nil),       // 10: xsight.PacketSample
	(*CriticalEvent)(nil),      // 11: xsight.CriticalEvent
	(*ControlMessage)(nil),     // 12: xsight.ControlMessage
	(*ConfigPush)(nil),         // 13: xsight.ConfigPush
	(*ConfigAck)(nil),          // 14: xsight.ConfigAck
	(*WatchConfig)(nil),        // 15: xsight.WatchConfig
	(*FlowListenerConfig)(nil), // 16: xsight.FlowListenerConfig
	(*FlowSourceConfig)(nil),   // 17: xsight.FlowSourceConfig
	(*WatchPrefix)(nil),        // 18: xsight.WatchPrefix
	(*HardThresholds)(nil),     // 19: xsight.HardThresholds
	nil,                        // 20: xsight.CriticalEvent.CountersEntry
	(*emptypb.Empty)(nil),      // 21: google.protobuf.Empty
}
var file_xsight_proto_depIdxs = []int32{
	15, // 0: xsight.HandshakeResponse.watch_config:type_name -> xsight.WatchConfig
	4,  // 1: xsight.StatsReport.ip_stats:type_name -> xsight.IPStats
	5,  // 2: xsight.StatsReport.prefix_stats:type_name -> xsight.PrefixStatsMsg
	7,  // 3: xsight.StatsReport.health:type_name -> xsight.NodeHealth
	8,  // 4: xsight.StatsReport.sampling_metrics:type_name -> xsight.SamplingMetrics
	6,  // 5: xsight.StatsReport.global_stats:type_name -> xsight.GlobalStatsMsg
	3,  // 6: xsight.StatsReport.top_flows:type_name -> xsight.FlowSample
	4,  // 7: xsight.StatsReport.src_ip_stats:type_name -> xsight.IPStats
	5,  // 8: xsight.StatsReport.src_prefix_stats:type_name -> xsight.PrefixStatsMsg
	10, // 9: xsight.SampleBatch.samples:type_name -> xsight.PacketSample
	20, // 10: xsight.CriticalEvent.counters:type_name -> xsight.CriticalEvent.CountersEntry
	13, // 11: xsight.ControlMessage.config_push:type_name -> xsight.ConfigPush
	14, // 12: xsight.ControlMessage.config_ack:type_name -> xsight.ConfigAck
	15, // 13: xsight.ConfigPush.watch_config:type_name -> xsight.WatchConfig
	18, // 14: xsight.WatchConfig.prefixes:type_name -> xsight.WatchPrefix
	19, // 15: xsight.WatchConfig.hard_thresholds:type_name -> xsight.HardThresholds
	16, // 16: xsight.WatchConfig.flow_listeners:type_name -> xsight.FlowListenerConfig
	17, // 17: xsight.FlowListenerConfig.sources:type_name -> xsight.FlowSourceConfig
	0,  // 18: xsight.XSightService.Handshake:input_type -> xsight.NodeHandshake
	2,  // 19: xsight.XSightService.StatsStream:input_type -> xsight.StatsReport
	9,  // 20: xsight.XSightService.SampleStream:input_type -> xsight.SampleBatch
	11, // 21: xsight.XSightService.CriticalEventStream:input_type -> xsight.CriticalEvent
	12, // 22: xsight.XSightService.ControlStream:input_type -> xsight.ControlMessage
	1,  // 23: xsight.XSightService.Handshake:output_type -> xsight.HandshakeResponse
	21, // 24: xsight.XSightService.StatsStream:output_type -> google.protobuf.Empty
	21, // 25: xsight.XSightService.SampleStream:output_type -> google.protobuf.Empty
	21, // 26: xsight.XSightService.CriticalEventStream:output_type -> google.protobuf.Empty
	12, // 27: xsight.XSightService.ControlStream:output_type -> xsight.ControlMessage
	23, // [23:28] is the sub-list for method output_type
	18, // [18:23] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_xsight_proto_init() }
func file_xsight_proto_init() {
	if File_xsight_proto != nil {
		return
	}
	file_xsight_proto_msgTypes[12].OneofWrappers = []any{
		(*ControlMessage_ConfigPush)(nil),
		(*ControlMessage_ConfigAck)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xsight_proto_rawDesc), len(file_xsight_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_xsight_proto_goTypes,
		DependencyIndexes: file_xsight_proto_depIdxs,
		MessageInfos:      file_xsight_proto_msgTypes,
	}.Build()
	File_xsight_proto = out.File
	file_xsight_proto_goTypes = nil
	file_xsight_proto_depIdxs = nil
}
