// xSight gRPC service definition.
// Shared between Node (client) and Controller (server).
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: xsight.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	XSightService_Handshake_FullMethodName           = "/xsight.XSightService/Handshake"
	XSightService_StatsStream_FullMethodName         = "/xsight.XSightService/StatsStream"
	XSightService_SampleStream_FullMethodName        = "/xsight.XSightService/SampleStream"
	XSightService_CriticalEventStream_FullMethodName = "/xsight.XSightService/CriticalEventStream"
	XSightService_ControlStream_FullMethodName       = "/xsight.XSightService/ControlStream"
)

// XSightServiceClient is the client API for XSightService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type XSightServiceClient interface {
	// Handshake: Node → Controller (unary, first step after connection)
	Handshake(ctx context.Context, in *NodeHandshake, opts ...grpc.CallOption) (*HandshakeResponse, error)
	// Three reporting streams: Node → Controller (client streaming)
	StatsStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[StatsReport, emptypb.Empty], error)
	SampleStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SampleBatch, emptypb.Empty], error)
	CriticalEventStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[CriticalEvent, emptypb.Empty], error)
	// Control channel: Controller ↔ Node (bidirectional streaming)
	ControlStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ControlMessage, ControlMessage], error)
}

type xSightServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewXSightServiceClient(cc grpc.ClientConnInterface) XSightServiceClient {
	return &xSightServiceClient{cc}
}

func (c *xSightServiceClient) Handshake(ctx context.Context, in *NodeHandshake, opts ...grpc.CallOption) (*HandshakeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandshakeResponse)
	err := c.cc.Invoke(ctx, XSightService_Handshake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xSightServiceClient) StatsStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[StatsReport, emptypb.Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &XSightService_ServiceDesc.Streams[0], XSightService_StatsStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StatsReport, emptypb.Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type XSightService_StatsStreamClient = grpc.ClientStreamingClient[StatsReport, emptypb.Empty]

func (c *xSightServiceClient) SampleStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SampleBatch, emptypb.Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &XSightService_ServiceDesc.Streams[1], XSightService_SampleStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SampleBatch, emptypb.Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type XSightService_SampleStreamClient = grpc.ClientStreamingClient[SampleBatch, emptypb.Empty]

func (c *xSightServiceClient) CriticalEventStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[CriticalEvent, emptypb.Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &XSightService_ServiceDesc.Streams[2], XSightService_CriticalEventStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CriticalEvent, emptypb.Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type XSightService_CriticalEventStreamClient = grpc.ClientStreamingClient[CriticalEvent, emptypb.Empty]

func (c *xSightServiceClient) ControlStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ControlMessage, ControlMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &XSightService_ServiceDesc.Streams[3], XSightService_ControlStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ControlMessage, ControlMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type XSightService_ControlStreamClient = grpc.BidiStreamingClient[ControlMessage, ControlMessage]

// XSightServiceServer is the server API for XSightService service.
// All implementations must embed UnimplementedXSightServiceServer
// for forward compatibility.
type XSightServiceServer interface {
	// Handshake: Node → Controller (unary, first step after connection)
	Handshake(context.Context, *NodeHandshake) (*HandshakeResponse, error)
	// Three reporting streams: Node → Controller (client streaming)
	StatsStream(grpc.ClientStreamingServer[StatsReport, emptypb.Empty]) error
	SampleStream(grpc.ClientStreamingServer[SampleBatch, emptypb.Empty]) error
	CriticalEventStream(grpc.ClientStreamingServer[CriticalEvent, emptypb.Empty]) error
	// Control channel: Controller ↔ Node (bidirectional streaming)
	ControlStream(grpc.BidiStreamingServer[ControlMessage, ControlMessage]) error
	mustEmbedUnimplementedXSightServiceServer()
}

// UnimplementedXSightServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedXSightServiceServer struct{}

func (UnimplementedXSightServiceServer) Handshake(context.Context, *NodeHandshake) (*HandshakeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Handshake not implemented")
}
func (UnimplementedXSightServiceServer) StatsStream(grpc.ClientStreamingServer[StatsReport, emptypb.Empty]) error {
	return status.Error(codes.Unimplemented, "method StatsStream not implemented")
}
func (UnimplementedXSightServiceServer) SampleStream(grpc.ClientStreamingServer[SampleBatch, emptypb.Empty]) error {
	return status.Error(codes.Unimplemented, "method SampleStream not implemented")
}
func (UnimplementedXSightServiceServer) CriticalEventStream(grpc.ClientStreamingServer[CriticalEvent, emptypb.Empty]) error {
	return status.Error(codes.Unimplemented, "method CriticalEventStream not implemented")
}
func (UnimplementedXSightServiceServer) ControlStream(grpc.BidiStreamingServer[ControlMessage, ControlMessage]) error {
	return status.Error(codes.Unimplemented, "method ControlStream not implemented")
}
func (UnimplementedXSightServiceServer) mustEmbedUnimplementedXSightServiceServer() {}
func (UnimplementedXSightServiceServer) testEmbeddedByValue()                       {}

// UnsafeXSightServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to XSightServiceServer will
// result in compilation errors.
type UnsafeXSightServiceServer interface {
	mustEmbedUnimplementedXSightServiceServer()
}

func RegisterXSightServiceServer(s grpc.ServiceRegistrar, srv XSightServiceServer) {
	// If the following call panics, it indicates UnimplementedXSightServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&XSightService_ServiceDesc, srv)
}

func _XSightService_Handshake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeHandshake)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XSightServiceServer).Handshake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XSightService_Handshake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XSightServiceServer).Handshake(ctx, req.(*NodeHandshake))
	}
	return interceptor(ctx, in, info, handler)
}

func _XSightService_StatsStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(XSightServiceServer).StatsStream(&grpc.GenericServerStream[StatsReport, emptypb.Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type XSightService_StatsStreamServer = grpc.ClientStreamingServer[StatsReport, emptypb.Empty]

func _XSightService_SampleStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(XSightServiceServer).SampleStream(&grpc.GenericServerStream[SampleBatch, emptypb.Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type XSightService_SampleStreamServer = grpc.ClientStreamingServer[SampleBatch, emptypb.Empty]

func _XSightService_CriticalEventStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(XSightServiceServer).CriticalEventStream(&grpc.GenericServerStream[CriticalEvent, emptypb.Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type XSightService_CriticalEventStreamServer = grpc.ClientStreamingServer[CriticalEvent, emptypb.Empty]

func _XSightService_ControlStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(XSightServiceServer).ControlStream(&grpc.GenericServerStream[ControlMessage, ControlMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type XSightService_ControlStreamServer = grpc.BidiStreamingServer[ControlMessage, ControlMessage]

// XSightService_ServiceDesc is the grpc.ServiceDesc for XSightService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var XSightService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xsight.XSightService",
	HandlerType: (*XSightServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Handshake",
			Handler:    _XSightService_Handshake_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StatsStream",
			Handler:       _XSightService_StatsStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "SampleStream",
			Handler:       _XSightService_SampleStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "CriticalEventStream",
			Handler:       _XSightService_CriticalEventStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ControlStream",
			Handler:       _XSightService_ControlStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "xsight.proto",
}
